apiVersion: v1
kind: Namespace
metadata:
  name: xai-staging
  labels:
    name: xai-staging
    environment: staging
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
    linkerd.io/inject: enabled
spec:
  finalizers:
    - kubernetes
