global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "xai-nodes"
    static_configs:
      - targets:
        - "xai-node1:9100"
        - "xai-node2:9100"
        - "xai-node3:9100"
        - "xai-node4:9100"
